Controllers/ReservaController.cs
using GS_GreenCycle.Filters;
using GS_GreenCycle.Helper;
using GS_GreenCycle.Models;
using GS_GreenCycle.Repositorio;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GS_GreenCycle.Controllers
{
    [PaginaParaUsuarioLogado]
    public class ReservaController : Controller
    {
        private readonly IReservaRepositorio _reservaRepositorio;
        private readonly ISessao _sessao;
        public ReservaController(IReservaRepositorio reservaRepositorio,
                                 ISessao sessao)
        {
            _reservaRepositorio = reservaRepositorio;
            _sessao = sessao;
        }

        public IActionResult Index()
        {
            UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
            List<ReservaModel> reservas = _reservaRepositorio.BuscarTodos(usuarioLogado.Id);
            return View(reservas);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            ReservaModel reserva = _reservaRepositorio.ListarPorId(id);
            return View(reserva);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            ReservaModel reserva = _reservaRepositorio.ListarPorId(id);
            return View(reserva);
        }

        
        public IActionResult Apagar(int id)
        {
            try 
            {
                bool apagado = _reservaRepositorio.Apagar(id);

                if(apagado)
                {
                    TempData["MensagemSucesso"] = "Reserva apagada com sucesso";
                }
                else
                {
                    TempData["MensagemErro"] = $"Sinto muito, um erro aconteceu ao tentar apagar sua reserva.";
                }
                return RedirectToAction("Index");
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Sinto muito, um erro aconteceu ao tentar apagar sua reserva. Detalhes do erro: {erro.Message}";
                return RedirectToAction("Index");
            }

        }
        
        [HttpPost]
        public IActionResult Criar(ReservaModel reserva)
        {
            try 
            {
                if (ModelState.IsValid)
                {
                    UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                    reserva.UsuarioId = usuarioLogado.Id;
                    _reservaRepositorio.Adicionar(reserva);
                    TempData["MensagemSucesso"] = "Reserva cadastrada com sucesso";
                    return RedirectToAction("Index");
                }

                return View(reserva);
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Sinto muito, um erro aconteceu ao tentar cadastrar sua reserva. Detalhes do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Alterar(ReservaModel reserva)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                    reserva.UsuarioId = usuarioLogado.Id;
                    reserva = _reservaRepositorio.Atualizar(reserva);
                    TempData["MensagemSucesso"] = "Reserva alterada com sucesso";
                    return RedirectToAction("Index");
                }

                return View("Editar", reserva);
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Sinto muito, um erro aconteceu ao tentar editar sua reserva. Detalhes do erro: {erro.Message}";
                return RedirectToAction("Index");
            }

            
        }
    }
}

Views/Reserva/ApagarConfirmacao.cshtml
@model ReservaModel
@{
    ViewData["Title"] = "Confirmação apagar a reserva";
}

<div class="text-center">
    <h3>Realmente deseja apagar a reserva do dia (@Model.dtRetirada)?</h3>
</div>

<div class="text-center">
    <a class="btn btn-primary" role="button" asp-controller="Reserva" asp-action="Index">Cancelar Exclusão</a>
    <a class="btn btn-danger" role="button" asp-controller="Reserva" asp-action="Apagar" asp-route-id="@Model.Id">Confirmar Exclusão</a>
</div>

Views/Reserva/Criar.cshtml
@model ReservaModel
@{
    ViewData["Title"] = "Cadastrar reservas";
}

<div class="text-center">

    <h1 class="display-4">Cadastrar reservas</h1>

</div>

<form asp-controller="Reserva" asp-action="Criar" method="post">

    <div class="mb-3">
        <label for="dtRetirada">Data de retirada</label>
        <input type="text" asp-for="dtRetirada" class="form-control" placeholder="Digite a data de retirada prevista">
        @Html.ValidationMessageFor(x => x.dtRetirada)
    </div>

    <div class="mb-3">
        <label for="hrRetirada">Hora de retirada</label>
        <input type="text" asp-for="hrRetirada" class="form-control" placeholder="Digite a hora de retirada prevista">
        @Html.ValidationMessageFor(x => x.hrRetirada)
    </div>

    <div class="mb-3">
        <label for="dtEntrega">Data de entrega</label>
        <input type="text" asp-for="dtEntrega" class="form-control" placeholder="Digite a data de entrega prevista">
        @Html.ValidationMessageFor(x => x.dtEntrega)
    </div>

    <div class="mb-3">
        <label for="hrEntrega">Hora de entrega</label>
        <input type="text" asp-for="hrEntrega" class="form-control" placeholder="Digite a hora de entrega prevista">
        @Html.ValidationMessageFor(x => x.hrEntrega)
    </div>

    <button type="submit" class="btn btn-primary">Adicionar</button>
    <a class="btn btn-secondary" asp-controller="Reserva" asp-action="Index" role="button">Voltar</a>
</form>

Views/Reserva/Editar.cshtml
@model ReservaModel
@{
    ViewData["Title"] = "Editar reserva";
}

<div class="text-center">

    <h1 class="display-4">Editar reservas</h1>

</div>

<form asp-controller="Reserva" asp-action="Alterar" method="post">

    <input type="hidden" asp-for="Id" />
    <div class="mb-3">
        <label for="dtRetirada">Data de retirada</label>
        <input type="text" asp-for="dtRetirada" class="form-control" placeholder="Digite a data de retirada prevista">
        @Html.ValidationMessageFor(x => x.dtRetirada)
    </div>

    <div class="mb-3">
        <label for="hrRetirada">Hora de retirada</label>
        <input type="text" asp-for="hrRetirada" class="form-control" placeholder="Digite a hora de retirada prevista">
        @Html.ValidationMessageFor(x => x.hrRetirada)
    </div>

    <div class="mb-3">
        <label for="dtEntrega">Data de entrega</label>
        <input type="text" asp-for="dtEntrega" class="form-control" placeholder="Digite a data de entrega prevista">
        @Html.ValidationMessageFor(x => x.dtEntrega)
    </div>

    <div class="mb-3">
        <label for="hrEntrega">Hora de entrega</label>
        <input type="text" asp-for="hrEntrega" class="form-control" placeholder="Digite a hora de entrega prevista">
        @Html.ValidationMessageFor(x => x.hrEntrega)
    </div>

    <button type="submit" class="btn btn-primary">Salvar</button>
    <a class="btn btn-secondary" asp-controller="Reserva" asp-action="Index" role="button">Voltar</a>
</form>

Views/Reserva/Index.cshtml
@model List<ReservaModel>
@{
    ViewData["Title"] = "Listagem de reservas";
}

<div class="d-grid gap-2 d-md-flex justify-content-md-start">
    <a class="btn btn-primary" role="button" asp-controller="Reserva" asp-action="Criar">Adcionar nova reserva</a>
</div>

<br />

<div class="text-center">

    @if(TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />

    <h1 class="display-4">Listagem de reservas</h1>

    <table class="display" id="table-reservas" style="width:100%">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Data de Retirada</th>
                <th scope="col">Hora de Retirada</th>
                <th scope="col">Data de Entrega</th>
                <th scope="col">Hora de Entrega</th>
                <th scope="col"></th>
            </tr>
        </thead>

        <tbody>
            @if(Model != null && Model.Any())
            {
                foreach (ReservaModel reserva in Model)
                {
                    <tr>
                        <th scope="row">@reserva.Id</th>
                        <td>@reserva.dtRetirada</td>
                        <td>@reserva.hrRetirada</td>
                        <td>@reserva.dtEntrega</td>
                        <td>@reserva.hrEntrega</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@reserva.Id" asp-controller="Reserva" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@reserva.Id" asp-controller="Reserva" asp-action="ApagarConfirmacao">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr class="odd"><td valign="top" colspan="5">Nenhuma reserva encontrada</td></tr>
            }

        </tbody>
    </table>

</div>